swagger: "2.0"
info:
  title: Hello Service
  description: Service to print hello
  version: ""
host: localhost:8000
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /:
    get:
      tags:
      - blog
      summary: list blog
      description: List all entries
      operationId: blog#list
      responses:
        "200":
          description: OK response.
          schema:
            type: array
            items:
              $ref: '#/definitions/StoredblogResponse'
      schemes:
      - http
    post:
      tags:
      - blog
      summary: create blog
      description: Add new blog and return its ID.
      operationId: blog#create
      parameters:
      - name: CreateRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/BlogCreateRequestBody'
      responses:
        "201":
          description: Created response.
          schema:
            $ref: '#/definitions/BlogCreateResponseBody'
      schemes:
      - http
  /{id}:
    delete:
      tags:
      - blog
      summary: remove blog
      description: Remove blog from storage
      operationId: blog#remove
      parameters:
      - name: id
        in: path
        description: ID of blog to remove
        required: true
        type: integer
      responses:
        "204":
          description: No Content response.
      schemes:
      - http
    patch:
      tags:
      - blog
      summary: update blog
      description: Updating the existing blog
      operationId: blog#update
      parameters:
      - name: id
        in: path
        description: ID of blog to be updated
        required: true
        type: integer
      - name: UpdateRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/BlogUpdateRequestBody'
          required:
          - name
          - comments
      responses:
        "204":
          description: No Content response.
      schemes:
      - http
  /{id}/comments:
    post:
      tags:
      - blog
      summary: add blog
      description: Add new blog and return its ID.
      operationId: blog#add
      parameters:
      - name: id
        in: path
        description: Id of blog
        required: true
        type: integer
      - name: AddRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/BlogAddRequestBody'
      responses:
        "201":
          description: Created response.
          schema:
            $ref: '#/definitions/BlogAddResponseBody'
      schemes:
      - http
  /openapi.json:
    get:
      tags:
      - blog
      summary: Download ./gen/http/openapi.json
      operationId: blog#/openapi.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
definitions:
  BlogAddRequestBody:
    title: BlogAddRequestBody
    type: object
    properties:
      comments:
        $ref: '#/definitions/CommentsRequestBody'
    example:
      comments:
        comments: Consequatur nesciunt.
        id: 3163100479
  BlogAddResponseBody:
    title: BlogAddResponseBody
    type: object
    properties:
      comments:
        $ref: '#/definitions/CommentsResponseBody'
      id:
        type: integer
        description: Id of blog
        example: 1227376400
        format: int32
    example:
      comments:
        comments: Est ut.
        id: 2591390728
      id: 2497136214
  BlogCreateRequestBody:
    title: BlogCreateRequestBody
    type: object
    properties:
      comments:
        type: array
        items:
          $ref: '#/definitions/CommentsRequestBody'
        description: Comments
        example:
        - comments: Consequatur nesciunt.
          id: 3163100479
        - comments: Consequatur nesciunt.
          id: 3163100479
        - comments: Consequatur nesciunt.
          id: 3163100479
        maxItems: 100
      id:
        type: integer
        description: ID of a person
        example: 3102958172
        format: int32
      name:
        type: string
        description: Name of person
        example: 8pj
        maxLength: 100
    example:
      comments:
      - comments: Consequatur nesciunt.
        id: 3163100479
      - comments: Consequatur nesciunt.
        id: 3163100479
      - comments: Consequatur nesciunt.
        id: 3163100479
      id: 1462081552
      name: gb4
  BlogCreateResponseBody:
    title: BlogCreateResponseBody
    type: object
    properties:
      comments:
        type: array
        items:
          $ref: '#/definitions/CommentsResponseBody'
        description: Comments
        example:
        - comments: Est ut.
          id: 2591390728
        - comments: Est ut.
          id: 2591390728
        - comments: Est ut.
          id: 2591390728
        maxItems: 100
      id:
        type: integer
        description: ID of a person
        example: 817814709
        format: int32
      name:
        type: string
        description: Name of person
        example: 4r0
        maxLength: 100
    example:
      comments:
      - comments: Est ut.
        id: 2591390728
      - comments: Est ut.
        id: 2591390728
      - comments: Est ut.
        id: 2591390728
      id: 1578833571
      name: xv5
  BlogUpdateRequestBody:
    title: BlogUpdateRequestBody
    type: object
    properties:
      comments:
        type: array
        items:
          $ref: '#/definitions/CommentsRequestBody'
        description: Comments to be updated
        example:
        - comments: Consequatur nesciunt.
          id: 3163100479
        - comments: Consequatur nesciunt.
          id: 3163100479
      name:
        type: string
        description: Details of blog to be updated
        example: Totam molestiae dolorum omnis impedit.
    example:
      comments:
      - comments: Consequatur nesciunt.
        id: 3163100479
      - comments: Consequatur nesciunt.
        id: 3163100479
      - comments: Consequatur nesciunt.
        id: 3163100479
      name: Soluta consequatur beatae soluta voluptatibus aut.
    required:
    - name
    - comments
  CommentsRequestBody:
    title: CommentsRequestBody
    type: object
    properties:
      comments:
        type: string
        description: Comment for the blog
        example: Iure velit.
      id:
        type: integer
        description: ID of a comment
        example: 4088298408
        format: int32
    description: Id and comments
    example:
      comments: Voluptate excepturi totam ducimus.
      id: 3298756195
  CommentsResponse:
    title: CommentsResponse
    type: object
    properties:
      comments:
        type: string
        description: Comment for the blog
        example: Et ullam nihil.
      id:
        type: integer
        description: ID of a comment
        example: 2331204871
        format: int32
    description: Id and comments
    example:
      comments: Numquam iste et eos voluptatem.
      id: 784797655
  CommentsResponseBody:
    title: CommentsResponseBody
    type: object
    properties:
      comments:
        type: string
        description: Comment for the blog
        example: At et.
      id:
        type: integer
        description: ID of a comment
        example: 914945699
        format: int32
    description: Id and comments
    example:
      comments: Aperiam id corporis voluptatibus inventore.
      id: 2468836870
  StoredblogResponse:
    title: 'Mediatype identifier: application/vnd.cellar.stored-blog; view=default'
    type: object
    properties:
      comments:
        type: array
        items:
          $ref: '#/definitions/CommentsResponse'
        description: Comments
        example:
        - comments: Dolores et.
          id: 1521196964
        - comments: Dolores et.
          id: 1521196964
        - comments: Dolores et.
          id: 1521196964
        maxItems: 100
      id:
        type: integer
        description: ID is the unique id of the blog.
        example: 1303724017
        format: int32
      name:
        type: string
        description: Name of person
        example: npp
        maxLength: 100
    description: A Storedblog describes a blog retrieved by the storage service. (default
      view)
    example:
      comments:
      - comments: Dolores et.
        id: 1521196964
      - comments: Dolores et.
        id: 1521196964
      - comments: Dolores et.
        id: 1521196964
      id: 3738307162
      name: lsc
    required:
    - id
    - name
