swagger: "2.0"
info:
  title: Blog Service
  description: Service to perform CRUD operations using goa
  version: ""
host: localhost:8000
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /:
    get:
      tags:
      - blog
      summary: list blog
      description: List all the blogs
      operationId: blog#list
      responses:
        "200":
          description: OK response.
          schema:
            type: array
            items:
              $ref: '#/definitions/StoredBlogResponse'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/BlogListDbErrorResponseBody'
      schemes:
      - http
    post:
      tags:
      - blog
      summary: create blog
      description: Add a new blog
      operationId: blog#create
      parameters:
      - name: CreateRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/BlogCreateRequestBody'
          required:
          - name
          - comments
      responses:
        "201":
          description: Created response.
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/BlogCreateDbErrorResponseBody'
      schemes:
      - http
  /{id}:
    get:
      tags:
      - blog
      summary: show blog
      description: Show blog based on the id given
      operationId: blog#show
      parameters:
      - name: id
        in: path
        description: ID of the blog to be fetched
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/BlogShowResponseBody'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/BlogShowDbErrorResponseBody'
      schemes:
      - http
    delete:
      tags:
      - blog
      summary: remove blog
      description: Delete a blog
      operationId: blog#remove
      parameters:
      - name: id
        in: path
        description: ID of blog to remove
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/BlogRemoveDbErrorResponseBody'
      schemes:
      - http
  /{id}/comments:
    patch:
      tags:
      - blog
      summary: add blog
      description: Add a new comment for a blog
      operationId: blog#add
      parameters:
      - name: id
        in: path
        description: Id of the blog
        required: true
        type: integer
      - name: AddRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/BlogAddRequestBody'
          required:
          - comments
      responses:
        "200":
          description: OK response.
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/BlogAddDbErrorResponseBody'
      schemes:
      - http
  /swagger/swagger.json:
    get:
      tags:
      - swagger
      summary: Download gen/http/openapi.json
      description: JSON document containing the API swagger definition
      operationId: swagger#/swagger/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
definitions:
  BlogAddDbErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: Unable to process db request (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  BlogAddRequestBody:
    title: BlogAddRequestBody
    type: object
    properties:
      comments:
        $ref: '#/definitions/CommentRequestBody'
    example:
      comments:
        comment: Aspernatur aliquid.
        id: 7401541539814418533
    required:
    - comments
  BlogCreateDbErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Unable to process db request (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  BlogCreateRequestBody:
    title: BlogCreateRequestBody
    type: object
    properties:
      comments:
        type: array
        items:
          $ref: '#/definitions/CommentRequestBody'
        description: Blog will have multiple comments
        example:
        - comment: Aspernatur aliquid.
          id: 7401541539814418533
        - comment: Aspernatur aliquid.
          id: 7401541539814418533
        - comment: Aspernatur aliquid.
          id: 7401541539814418533
      name:
        type: string
        description: Name of person
        example: Voluptas quo.
    example:
      comments:
      - comment: Aspernatur aliquid.
        id: 7401541539814418533
      - comment: Aspernatur aliquid.
        id: 7401541539814418533
      - comment: Aspernatur aliquid.
        id: 7401541539814418533
      - comment: Aspernatur aliquid.
        id: 7401541539814418533
      name: Numquam iste et eos voluptatem.
    required:
    - name
    - comments
  BlogListDbErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Unable to process db request (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  BlogRemoveDbErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: Unable to process db request (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  BlogShowDbErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Unable to process db request (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  BlogShowResponseBody:
    title: 'Mediatype identifier: application/vnd.goa-crud.stored-blog; view=default'
    type: object
    properties:
      comments:
        type: array
        items:
          $ref: '#/definitions/StoredCommentResponseBody'
        description: Blog with multiple comments
        example:
        - comment: Inventore ea ratione at et possimus.
          id: 5016661606024321144
        - comment: Inventore ea ratione at et possimus.
          id: 5016661606024321144
        - comment: Inventore ea ratione at et possimus.
          id: 5016661606024321144
        - comment: Inventore ea ratione at et possimus.
          id: 5016661606024321144
      id:
        type: integer
        description: ID is the unique id of the blog
        example: 15507272056637408931
        format: int64
      name:
        type: string
        description: Name of person
        example: Consequatur id nihil molestiae quis.
    description: ShowResponseBody result type (default view)
    example:
      comments:
      - comment: Inventore ea ratione at et possimus.
        id: 5016661606024321144
      - comment: Inventore ea ratione at et possimus.
        id: 5016661606024321144
      - comment: Inventore ea ratione at et possimus.
        id: 5016661606024321144
      id: 13369826350771179092
      name: Qui dolor autem inventore rerum.
    required:
    - id
    - name
    - comments
  CommentRequestBody:
    title: CommentRequestBody
    type: object
    properties:
      comment:
        type: string
        description: Comment for the blog
        example: Rem atque.
      id:
        type: integer
        description: ID of a comment
        example: 7330576659502459226
        format: int64
    description: A blog will have multiple comments
    example:
      comment: Et ullam nihil.
      id: 14229596379368594935
    required:
    - comment
  StoredBlogResponse:
    title: 'Mediatype identifier: application/vnd.goa-crud.stored-blog; view=default'
    type: object
    properties:
      comments:
        type: array
        items:
          $ref: '#/definitions/StoredCommentResponse'
        description: Blog with multiple comments
        example:
        - comment: Soluta aut dolorum fuga rerum et et.
          id: 12139931803128476515
        - comment: Soluta aut dolorum fuga rerum et et.
          id: 12139931803128476515
        - comment: Soluta aut dolorum fuga rerum et et.
          id: 12139931803128476515
      id:
        type: integer
        description: ID is the unique id of the blog
        example: 8027953502973288132
        format: int64
      name:
        type: string
        description: Name of person
        example: Dolor quos distinctio blanditiis cum.
    description: A Blog describes a blog retrieved by the storage service. (default
      view)
    example:
      comments:
      - comment: Soluta aut dolorum fuga rerum et et.
        id: 12139931803128476515
      - comment: Soluta aut dolorum fuga rerum et et.
        id: 12139931803128476515
      - comment: Soluta aut dolorum fuga rerum et et.
        id: 12139931803128476515
      - comment: Soluta aut dolorum fuga rerum et et.
        id: 12139931803128476515
      id: 14585931223794749621
      name: Perferendis dolores temporibus labore.
    required:
    - id
    - name
    - comments
  StoredCommentResponse:
    title: StoredCommentResponse
    type: object
    properties:
      comment:
        type: string
        description: Comment for the blog
        example: Dolorum omnis impedit ipsam cupiditate soluta consequatur.
      id:
        type: integer
        description: ID of a comment
        example: 3148352589434995641
        format: int64
    description: A blog will have multiple comments
    example:
      comment: Voluptatibus aut tempore.
      id: 1114461028488156773
    required:
    - id
    - comment
  StoredCommentResponseBody:
    title: StoredCommentResponseBody
    type: object
    properties:
      comment:
        type: string
        description: Comment for the blog
        example: Nobis est omnis consequatur rerum.
      id:
        type: integer
        description: ID of a comment
        example: 524712405222133304
        format: int64
    description: A blog will have multiple comments
    example:
      comment: Id aut assumenda et.
      id: 16404257844892318138
    required:
    - id
    - comment
