swagger: "2.0"
info:
  title: Blog Service
  description: Service to perform CRUD operations using goa
  version: ""
host: localhost:8000
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /:
    get:
      tags:
      - blog
      summary: list blog
      description: List all entries
      operationId: blog#list
      responses:
        "200":
          description: OK response.
          schema:
            type: array
            items:
              $ref: '#/definitions/StoredblogResponse'
      schemes:
      - http
    post:
      tags:
      - blog
      summary: create blog
      description: Add new blog and return its ID.
      operationId: blog#create
      parameters:
      - name: CreateRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/BlogCreateRequestBody'
      responses:
        "201":
          description: Created response.
          schema:
            $ref: '#/definitions/BlogCreateResponseBody'
      schemes:
      - http
  /{id}:
    get:
      tags:
      - blog
      summary: show blog
      description: Show blog based on the id given
      operationId: blog#show
      parameters:
      - name: id
        in: path
        description: ID of a person
        required: true
        type: integer
      - name: ShowRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/BlogShowRequestBody'
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/BlogShowResponseBody'
      schemes:
      - http
    delete:
      tags:
      - blog
      summary: remove blog
      description: Remove blog from storage
      operationId: blog#remove
      parameters:
      - name: id
        in: path
        description: ID of blog to remove
        required: true
        type: integer
      responses:
        "204":
          description: No Content response.
      schemes:
      - http
    patch:
      tags:
      - blog
      summary: update blog
      description: Updating the existing blog
      operationId: blog#update
      parameters:
      - name: id
        in: path
        description: ID of blog to be updated
        required: true
        type: integer
      - name: UpdateRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/BlogUpdateRequestBody'
          required:
          - name
          - comments
      responses:
        "204":
          description: No Content response.
      schemes:
      - http
  /{id}/comments:
    post:
      tags:
      - blog
      summary: add blog
      description: Add new blog and return its ID.
      operationId: blog#add
      parameters:
      - name: id
        in: path
        description: Id of blog
        required: true
        type: integer
      - name: AddRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/BlogAddRequestBody'
      responses:
        "201":
          description: Created response.
          schema:
            $ref: '#/definitions/BlogAddResponseBody'
      schemes:
      - http
  /oauth/redirect:
    post:
      tags:
      - blog
      summary: oauth blog
      description: Github authentication to post a new blog
      operationId: blog#oauth
      parameters:
      - name: OauthRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/BlogOauthRequestBody'
      responses:
        "201":
          description: Created response.
          schema:
            type: string
      schemes:
      - http
  /openapi.json:
    get:
      tags:
      - blog
      summary: Download ./gen/http/openapi.json
      operationId: blog#/openapi.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
definitions:
  BlogAddRequestBody:
    title: BlogAddRequestBody
    type: object
    properties:
      comments:
        $ref: '#/definitions/CommentsRequestBody'
    example:
      comments:
        comments: Vel nam dolores et minus.
        id: 339538165
  BlogAddResponseBody:
    title: BlogAddResponseBody
    type: object
    properties:
      comments:
        $ref: '#/definitions/CommentsResponseBody'
      id:
        type: integer
        description: Id of blog
        example: 3125156104
        format: int32
    example:
      comments:
        comments: Dolorum fuga.
        id: 1591530152
      id: 4136160167
  BlogCreateRequestBody:
    title: BlogCreateRequestBody
    type: object
    properties:
      comments:
        type: array
        items:
          $ref: '#/definitions/CommentsRequestBody'
        description: Comments
        example:
        - comments: Vel nam dolores et minus.
          id: 339538165
        - comments: Vel nam dolores et minus.
          id: 339538165
        - comments: Vel nam dolores et minus.
          id: 339538165
        maxItems: 100
      id:
        type: integer
        description: ID of a person
        example: 4017985820
        format: int32
      name:
        type: string
        description: Name of person
        example: s09
        maxLength: 100
    example:
      comments:
      - comments: Vel nam dolores et minus.
        id: 339538165
      - comments: Vel nam dolores et minus.
        id: 339538165
      - comments: Vel nam dolores et minus.
        id: 339538165
      id: 998969093
      name: obn
  BlogCreateResponseBody:
    title: BlogCreateResponseBody
    type: object
    properties:
      comments:
        type: array
        items:
          $ref: '#/definitions/CommentsResponseBody'
        description: Comments
        example:
        - comments: Dolorum fuga.
          id: 1591530152
        - comments: Dolorum fuga.
          id: 1591530152
        - comments: Dolorum fuga.
          id: 1591530152
        maxItems: 100
      id:
        type: integer
        description: ID of a person
        example: 3050217864
        format: int32
      name:
        type: string
        description: Name of person
        example: b8v
        maxLength: 100
    example:
      comments:
      - comments: Dolorum fuga.
        id: 1591530152
      - comments: Dolorum fuga.
        id: 1591530152
      - comments: Dolorum fuga.
        id: 1591530152
      id: 2868590302
      name: xdl
  BlogOauthRequestBody:
    title: BlogOauthRequestBody
    type: object
    properties:
      token:
        type: string
        description: Access github token
        example: Sed autem vel saepe voluptas necessitatibus.
    example:
      token: Nam minus nesciunt odit eveniet sed est.
  BlogShowRequestBody:
    title: BlogShowRequestBody
    type: object
    properties:
      comments:
        type: array
        items:
          $ref: '#/definitions/CommentsRequestBody'
        description: Comments
        example:
        - comments: Vel nam dolores et minus.
          id: 339538165
        - comments: Vel nam dolores et minus.
          id: 339538165
        - comments: Vel nam dolores et minus.
          id: 339538165
        maxItems: 100
      name:
        type: string
        description: Name of person
        example: eo9
        maxLength: 100
    example:
      comments:
      - comments: Vel nam dolores et minus.
        id: 339538165
      - comments: Vel nam dolores et minus.
        id: 339538165
      - comments: Vel nam dolores et minus.
        id: 339538165
      name: iis
  BlogShowResponseBody:
    title: BlogShowResponseBody
    type: object
    properties:
      comments:
        type: array
        items:
          $ref: '#/definitions/CommentsResponseBody'
        description: Comments
        example:
        - comments: Dolorum fuga.
          id: 1591530152
        - comments: Dolorum fuga.
          id: 1591530152
        - comments: Dolorum fuga.
          id: 1591530152
        maxItems: 100
      id:
        type: integer
        description: ID of a person
        example: 955661082
        format: int32
      name:
        type: string
        description: Name of person
        example: mpt
        maxLength: 100
    example:
      comments:
      - comments: Dolorum fuga.
        id: 1591530152
      - comments: Dolorum fuga.
        id: 1591530152
      - comments: Dolorum fuga.
        id: 1591530152
      id: 3426442364
      name: o6j
  BlogUpdateRequestBody:
    title: BlogUpdateRequestBody
    type: object
    properties:
      comments:
        type: array
        items:
          $ref: '#/definitions/CommentsRequestBody'
        description: Comments to be updated
        example:
        - comments: Vel nam dolores et minus.
          id: 339538165
        - comments: Vel nam dolores et minus.
          id: 339538165
        - comments: Vel nam dolores et minus.
          id: 339538165
        - comments: Vel nam dolores et minus.
          id: 339538165
      name:
        type: string
        description: Details of blog to be updated
        example: Molestiae et iusto.
    example:
      comments:
      - comments: Vel nam dolores et minus.
        id: 339538165
      - comments: Vel nam dolores et minus.
        id: 339538165
      - comments: Vel nam dolores et minus.
        id: 339538165
      - comments: Vel nam dolores et minus.
        id: 339538165
      name: Temporibus quam quis.
    required:
    - name
    - comments
  CommentsRequestBody:
    title: CommentsRequestBody
    type: object
    properties:
      comments:
        type: string
        description: Comment for the blog
        example: Beatae soluta voluptatibus aut tempore.
      id:
        type: integer
        description: ID of a comment
        example: 4010003907
        format: int32
    description: Id and comments
    example:
      comments: Sequi perferendis dolores temporibus labore.
      id: 1227376400
  CommentsResponse:
    title: CommentsResponse
    type: object
    properties:
      comments:
        type: string
        description: Comment for the blog
        example: Et et nobis est omnis consequatur rerum.
      id:
        type: integer
        description: ID of a comment
        example: 2753009699
        format: int32
    description: Id and comments
    example:
      comments: Id aut assumenda et.
      id: 3343860529
  CommentsResponseBody:
    title: CommentsResponseBody
    type: object
    properties:
      comments:
        type: string
        description: Comment for the blog
        example: Et tenetur numquam iste et eos.
      id:
        type: integer
        description: ID of a comment
        example: 3407509870
        format: int32
    description: Id and comments
    example:
      comments: Necessitatibus id.
      id: 3480606670
  StoredblogResponse:
    title: 'Mediatype identifier: application/vnd.cellar.stored-blog; view=default'
    type: object
    properties:
      comments:
        type: array
        items:
          $ref: '#/definitions/CommentsResponse'
        description: Comments
        example:
        - comments: Eveniet non eaque omnis et inventore ea.
          id: 1647799179
        - comments: Eveniet non eaque omnis et inventore ea.
          id: 1647799179
        - comments: Eveniet non eaque omnis et inventore ea.
          id: 1647799179
        maxItems: 100
      id:
        type: integer
        description: ID is the unique id of the blog.
        example: 2926168972
        format: int32
      name:
        type: string
        description: Name of person
        example: 3wh
        maxLength: 100
    description: A Storedblog describes a blog retrieved by the storage service. (default
      view)
    example:
      comments:
      - comments: Eveniet non eaque omnis et inventore ea.
        id: 1647799179
      - comments: Eveniet non eaque omnis et inventore ea.
        id: 1647799179
      - comments: Eveniet non eaque omnis et inventore ea.
        id: 1647799179
      id: 1930843253
      name: 51m
    required:
    - id
    - name
